[feature/#27] github oauth와 jwt 처리 기능 추가
woowa-techcamp-2021/cashbook-19 pull request #36
Opened 2021-07-29 15:11 UTC by TsooranKim

## 🔨 작업내역

- routing(controller) - service - model 라인 형성
- typedi를 사용한 Dependency Injection과 Inversion of Control 구성
- github oauth 처리
- jwt 인증, 재인증 로직 작성
- jwt 인증, 인가 middleware 작성

## 🖌 리뷰포인트

- routing - service - model 구성이 괜찮은지
- jwt 처리 부분이 괜찮은지

## 🧐 어려웠던 점이나 하고 싶은 말

생소한것들 붙들고 씨름을 하니 오래걸리는군요 ㅠㅠ

## ⏰ 작업시간

8시간

2021-07-29 15:42 UTC, Kyun2da requested changes
di를 쓰니까 확실히 코드가 깔끔해지네요! 좋은 라이브러리 사용하신 것 같습니다.

제안 사항은 url 상수화가 다인 것 같구요

그 api/v1폴더에 index.ts쪽이 전부 미들웨어 같던데 나중에 미들웨어 폴더로 옮겨서 관리하는 것도 좋을 것 같아요. 라우트 폴더에는 라우팅만 해주는게 맞지 않나 싶습니다!

2021-07-29 15:42 UTC, Kyun2da commented on server/.env.sample
> +JWT_REFRESH_EXPIRES_IN=604800
이 부분은 그냥 저 보라고 샘플 값 넣어 노신건가요? 노출되도 상관 없는 값이겠죵?

2021-07-29 15:42 UTC, Kyun2da commented on server/src/core/error.ts
> +/* eslint-disable import/prefer-default-export */
엇 이것은 무엇일까요?

2021-07-29 15:42 UTC, Kyun2da commented on server/src/loaders/expressLoader.ts
> +        message: process.env.NODE_ENV === 'development' ? err.message : 'INTERNAL_SERVER_ERROR',
이런 부분 너무 에러처리 깔끔하네요.. 존경합니다 👍

2021-07-29 15:42 UTC, Kyun2da commented on server/src/services/oauth.ts
> +        'https://github.com/login/oauth/access_token',
이 부분 상수로 따로 빼는 것은 어떨까요?

2021-07-29 15:42 UTC, Kyun2da commented on server/src/services/oauth.ts
> +      const userRes = await axios.get('https://api.github.com/user', {
이 부분도요!

2021-07-29 15:42 UTC, Kyun2da commented on server/src/services/oauth.ts
> +@Service()
ㅋㅋ typedi 라이브러리 di 재미있네요 꿀 라이브러리 인것 같아요 service 넣어주고 Container.get으로 받아오는 로직이군요? ㅋㅋㅋ 👍

2021-07-30 00:48 UTC, TsooranKim commented on server/.env.sample
> +JWT_REFRESH_EXPIRES_IN=604800
시크릿 말고는 노출되도 상관없는 값이에요 ㅎㅎ

2021-07-30 00:48 UTC, TsooranKim commented on server/src/core/error.ts
> +/* eslint-disable import/prefer-default-export */
한 파일 내에서만 eslint 특정 기능을 끄는 주석입니다~

2021-07-30 01:14 UTC, TsooranKim commented on server/src/services/oauth.ts
> +      const userRes = await axios.get('https://api.github.com/user', {
네~ 반영하겠습니다~

2021-07-30 01:31 UTC, TsooranKim commented on server/src/services/oauth.ts
> +        'https://github.com/login/oauth/access_token',
> 그 api/v1폴더에 index.ts쪽이 전부 미들웨어 같던데 나중에 미들웨어 폴더로 옮겨서 관리하는 것도 좋을 것 같아요. 라우트 폴더에는 라우팅만 해주는게 맞지 않나 싶습니다!

넵 미들웨어 함수는 따로 빼서 분리했습니다~

> 아! 그리고 제가 돌려보려고 npm install 하는데 package-lock.json 이 쫙 업데이트가 되네용 아마 제가 npm 최신 버전이라 "lockfileVersion": 2, 로바뀌면서 생기는 문제 같은데 이거를 협업하면서 계속 충돌이 나지는 않을련지 걱정이 되어 계속 바뀔때마다 커밋해도 되는 것인지 여쭤봅니다.
> 
> 제 npm 버전은 7.20.1입니다!

이것도 제 개발환경에서 npm 최신화해서 반영했습니다~

2021-07-30 01:31 UTC, TsooranKim commented
> 그 api/v1폴더에 index.ts쪽이 전부 미들웨어 같던데 나중에 미들웨어 폴더로 옮겨서 관리하는 것도 좋을 것 같아요. 라우트 폴더에는 라우팅만 해주는게 맞지 않나 싶습니다!

넵 미들웨어 함수는 따로 빼서 분리했습니다~

> 아! 그리고 제가 돌려보려고 npm install 하는데 package-lock.json 이 쫙 업데이트가 되네용 아마 제가 npm 최신 버전이라 "lockfileVersion": 2, 로바뀌면서 생기는 문제 같은데 이거를 협업하면서 계속 충돌이 나지는 않을련지 걱정이 되어 계속 바뀔때마다 커밋해도 되는 것인지 여쭤봅니다.
> 
> 제 npm 버전은 7.20.1입니다!

이것도 제 개발환경에서 npm 최신화해서 반영했습니다~

2021-07-30 02:06 UTC, Kyun2da approved these changes

2021-07-30 02:12 UTC, merged

2021-07-30 05:25 UTC, jiyong1 commented
풀리퀘 템플릿 엄청 깔끔하네요..
보고 배웁니당 ㅎㅎ